name: Build CI

on:
  workflow_dispatch:

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@rc
      with:
        egress-policy: block
        allowed-endpoints: >
          *.ubuntu.com:80
          debian.org:80
          github.com:443
          *.microsoft.com:443
          ppa.launchpadcontent.net:443
          www.debian.org:443
          yahoo.com:1025

    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - name: update package information
      run: sudo apt-get update
    - name: install dependencies
      run: sudo apt-get install gcc-12 libapparmor-dev libselinux1-dev expect xzdec
    - name: configure
      run: CC=gcc-12 ./configure --enable-fatal-warnings --enable-analyzer --enable-apparmor --enable-selinux --prefix=/usr
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - name: print version
      run: command -V firejail && firejail --version
    - name: run tests
      run: SHELL=/bin/bash make test-github
